sudo: false
language: c

install:
    - echo "CONFIG_TARGET_pistachio=y" > ./.config
    - echo "CONFIG_TARGET_pistachio_marduk=y" >> ./.config

script:
    - make defconfig
    - make -j 20 & PID=$!; while kill -0 $PID >/dev/null 2>&1 ; do sleep 300; echo "MARK" >&2 ; done
